apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: {{ .Values.project.name }}
  sources:
    - repoURL: https://kedacore.github.io/charts
      chart: keda
      targetRevision: 2.18.0
      helm:
        releaseName: keda
        valueFiles:
          - '$repo/apps/00-operators/keda/values.yaml'
    - repoURL: https://github.com/kuanchoulai10/argocd-demo
      targetRevision: main
      ref: repo
  destination:
    name: {{ .Values.spec.destination.name }}
    namespace: keda
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true