apiVersion: v2
name: retail-lakehouse
description: A Helm chart for ArgoCD application management with operators and applications
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - argocd
  - gitops
  - kubernetes
  - operators
home: https://github.com/kuanchoulai10/retail-lakehouse
sources:
  - https://github.com/kuanchoulai10/retail-lakehouse
maintainers:
  - name: ArgoCD Demo Team